---
# This playbook uses the win_get_url module to download a simple HTML file for IIS
- name: Download simple web site 
  hosts: all 

  gather_facts: false
  tasks:
    - name: Download simple web site to 'C:\inetpub\wwwroot\index.html'
      #win_get_url:
      #  url: 'https://raw.githubusercontent.com/jedrington/ansible-examples/master/windows/files/index.html'
      #  dest: 'C:\inetpub\wwwroot\index.html'
      win_template:
        src: '/files/index.html.j2'
        dest: 'C:\inetpub\wwwroot\index.html'
